CH_CAR_PFM/Controllers/AppFormPayController.cs
using CH_CAR_PFM.Helps;
using CH_CAR_PFM.Models;
using CH_CAR_PFM.Models.AppFormPay;
using CH_CAR_PFM.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CH_CAR_PFM.Controllers
{
    /// <summary>
    /// APP 繳款 Controller
    /// </summary>
    public class AppFormPayController : BaseController
    {
        /// <summary>
        /// 取得標的物資料(繳款紀錄)
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/GetArRecLv1")]
        public async Task<ActionResult> GetArRecLv1()
        {
            GetCustInfoInput cusModel = new GetCustInfoInput();
            GetCustInfoOutput cusResult = new GetCustInfoOutput();

            if (this.TokenVerify.Id == string.Empty)
            {
                cusModel = new GetCustInfoInput
                {
                    MBR_ID = this.TokenVerify.MbrId,
                    MbrId = this.TokenVerify.MbrId,
                    DevId = this.TokenVerify.DevId,
                    Token = this.TokenVerify.Token
                };

                // 取得會員資料
                HomeService homeService = new HomeService();
                cusResult = await homeService.GetCustInfo(cusModel);

                if(cusResult.ID != string.Empty)
                {
                    // 取得全資料
                    InitOutput initOutput = await homeService.INIT(cusResult.ID);

                    System.Web.HttpCookie AridCookie = this.AirdCookie(cusResult.ID ?? string.Empty, this.TokenVerify.MbrId, this.TokenVerify.DevId, this.TokenVerify.Token, initOutput?.CUST_ID ?? string.Empty, initOutput?.CNTRT_NO ?? string.Empty);
                    this.Response.Cookies.Add(AridCookie);
                }               
            }


            GetArRecLvInput model = new GetArRecLvInput
            {
                //ID = this.TokenVerify.Id,
                ID = !string.IsNullOrEmpty(cusResult.ID) ? cusResult.ID : this.TokenVerify.Id,
                COMP_ID = this.TokenVerify.CustId,
                MbrId = this.TokenVerify.MbrId,
                DevId = this.TokenVerify.DevId,
                Token = this.TokenVerify.Token,
                SYS_ID = Common.GetSysId()
            };

            AppFormPayService appFormPayService = new AppFormPayService();
            BaseListResult<GetArRecLvOutput> result = await appFormPayService.GetArRecLv1(model);

            return this.Json(result);
        }

        /// <summary>
        /// 取得往來明細清單(未繳/逾期)
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/GetArLv1New")]
        public async Task<ActionResult> GetArLv1New()
        {
            var dataList = new List<GetArRecLvNewOutput>();
            var data = new GetArRecLvNewOutput();
            var ar = new ArList();
            var arList = new List<ArList>();

            GetArRecLvInput model = new GetArRecLvInput
            {
                ID = this.TokenVerify.Id,
                COMP_ID = this.TokenVerify.CustId,
                MbrId = this.TokenVerify.MbrId,
                DevId = this.TokenVerify.DevId,
                Token = this.TokenVerify.Token,
                SYS_ID = Common.GetSysId()
            };

            AppFormPayService appFormPayService = new AppFormPayService();
            BaseListResult<GetArRecLvNewOutput> result = await appFormPayService.GetArLv1New(model);

            foreach (var item in result.Data)
            {
                data = new GetArRecLvNewOutput();
                arList = new List<ArList>();

                data.IS_PROXY = item.IS_PROXY;
                data.PAYABLE_AMT = item.PAYABLE_AMT;
                data.CNTRT_NO = item.CNTRT_NO;
                data.OBJ_ITEMS = item.OBJ_ITEMS;
                data.PAYMENT_DESC = item.PAYMENT_DESC;
                data.AR_DT = item.AR_DT;
                data.AR_AMT = item.AR_AMT;
                data.TTL_AMT = item.TTL_AMT;
                data.OBJ_NAME = item.OBJ_NAME;
                data.VENDER_NME = item.VENDER_NME;
                data.BUY_DT = item.BUY_DT;
                data.IS_FINISH = item.IS_FINISH;

                foreach (var itemList in item.AR_LIST)
                {
                    ar = new ArList();
                    ar.AR_AMT = itemList.AR_AMT;
                    ar.AR_CNT = itemList.AR_CNT;
                    ar.AR_DESC = itemList.AR_DESC;
                    ar.AR_DT = itemList.AR_DT;
                    ar.AR_ID = itemList.AR_ID;
                    ar.AR_PAYDT = itemList.AR_PAYDT;
                    ar.AR_PK = itemList.AR_PK;
                    ar.ISCURRENT = itemList.ISCURRENT;
                    ar.OVERDUE = itemList.OVERDUE;
                    ar.PAYMENT_STATUS = itemList.PAYMENT_STATUS;

                    if (item.IS_PROXY == "Y" && itemList.PAYMENT_STATUS == "1" && itemList.ISCURRENT == "Y")
                    {
                        data.PAYABLE_AMT = 0;
                        data.AR_DT = itemList.AR_DT;
                    }

                    arList.Add(ar);
                }

                data.AR_LIST = arList;
                dataList.Add(data);
            }

            result.Data = dataList;

            return this.Json(result);
        }

        /// <summary>
        /// 驗證最後送出AR資訊是否正確
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/ValidateArPay")]
        public async Task<ActionResult> ValidateArPay(int[] arIdItems, Decimal arAmtSum, string payMethod, string CNTRT_NO)
        {
            ValidArPayInput model = new ValidArPayInput
            {
                CNTRT_NO = CNTRT_NO,
                AR_ID_ITEMS = arIdItems,
                AR_AMT_SUM = arAmtSum,
                PAY_METHOD = payMethod,
                MbrId = this.TokenVerify.MbrId,
                DevId = this.TokenVerify.DevId,
                Token = this.TokenVerify.Token,
                SYS_ID = Common.GetSysId()
            };

            AppFormPayService appFormPayService = new AppFormPayService();
            BaseResult<ValidArPayOutput> result = await appFormPayService.ValidateArPay(model);

            return this.Json(result);
        }

        /// <summary>
        /// 取得 7-11 超商繳費 BarCode 圖片
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/Get711BarCodeImg")]
        public async Task<ActionResult> Get711BarCodeImg(List<ArList> arList)
        {
            BaseResult<MergeBarcodeOutput> resultModel = await this.GetMergeBarCodeData(arList);
            if (resultModel.Result.ReturnCode != 0)
            {
                return null;
            }

            // 7-11 要自行抽換 barCode 前四碼
            string checkBarCodeHead = ConfigurationManager.AppSettings["CheckBarCodeHead"];
            string barCodeHead = barCodeHead = ConfigurationManager.AppSettings["711BarCodeHead"];

            // 如果前四碼不是G800的話，就抽換成創鉅的 G910
            if (resultModel.Data.BARCODE2.Substring(0, 4) != checkBarCodeHead)
            {
                barCodeHead = ConfigurationManager.AppSettings["711BarCodeHead2"];
            }

            string barCode2 = barCodeHead + resultModel.Data.BARCODE2.Substring(4, resultModel.Data.BARCODE2.Length - 4);
            int totalAmount = arList.Sum(x => int.Parse(x.AR_AMT));

            Barcode711Input model = new Barcode711Input
            {
                COMP_ID = this.TokenVerify.CustId,
                Oino = resultModel.Data.OINO,
                OL_Amount = totalAmount.ToString(),
                OL_Code_2 = barCode2,
                TraceID = barCode2,
                MbrId = this.TokenVerify.MbrId,
                DevId = this.TokenVerify.DevId,
                Token = this.TokenVerify.Token,
                SYS_ID = Common.GetSysId()
            };

            AppFormPayService appFormPayService = new AppFormPayService();
            BaseResult<Barcode711Output> result = await appFormPayService.Get711BarCodeImg(model);

            return this.Json(result);
        }

        /// <summary>
        /// 取得超商繳費 BarCode
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/GetMergeBarCode")]
        public async Task<ActionResult> GetMergeBarCode(List<ArList> arList)
        {
            BaseResult<MergeBarcodeOutput> result = await this.GetMergeBarCodeData(arList);

            return this.Json(result);
        }

        /// <summary>
        /// 取得繳款紀錄(含已繳項目)
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("AppFormPay/GetArRec")]
        public async Task<ActionResult> GetArRec(string cntrtNo)
        {
            GetArRecInput model = new GetArRecInput
            {
                ID = this.TokenVerify.Id,
                CNTRT_NO = cntrtNo,
                COMP_ID = this.TokenVerify.CustId,
                MbrId = this.TokenVerify.MbrId,
                DevId = this.TokenVerify.DevId,
                Token = this.TokenVerify.Token,
                SYS_ID = Common.GetSysId()
            };

            AppFormPayService appFormPayService = new AppFormPayService();
            BaseListResult<GetArRecOutput> result = await appFormPayService.GetArRec(model);

            return this.Json(result);
        }

        [HttpGet]
        [Route("AppFormPay/GetBarCodeImage")]
        public string GetBarCodeImage(string barcodeStr)
        {
            //產生圖片檔案
            string SavePath = @"C:\Outsourcing\barcode.png";
            //Barcode條碼需在前後加上*字號代表開始與結束

CH_CAR_PFM/Controllers/HomeController.cs
using CH_CAR_PFM.Models;
using CH_CAR_PFM.Models.AppFormPay;
using CH_CAR_PFM.Service;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CH_CAR_PFM.Controllers
{
    public class HomeController : BaseController
    {
        /// <summary>
        /// 繳款
        /// </summary>
        /// <param name="MbrId">會員編號(持久登入驗證)</param>
        /// <param name="DevId">裝置編號(持久登入驗證)</param>
        /// <param name="Token">持久登入用Token(持久登入驗證)</param>
        /// <returns></returns>
        public async Task<ActionResult> Index(string MbrId, string DevId, string Token)
        {
            if (string.IsNullOrEmpty(MbrId) && string.IsNullOrEmpty(this.TokenVerify?.MbrId))
            {
                return this.Json(new { isError = true, message = "查無資料!!!" }, JsonRequestBehavior.AllowGet);
            }

            GetCustInfoInput model = new GetCustInfoInput
            {
                MBR_ID = string.IsNullOrEmpty(MbrId) ? this.TokenVerify.MbrId : MbrId,
                MbrId = string.IsNullOrEmpty(MbrId) ? this.TokenVerify.MbrId : MbrId,
                DevId = string.IsNullOrEmpty(DevId) ? this.TokenVerify.DevId : DevId,
                Token = string.IsNullOrEmpty(Token) ? this.TokenVerify.Token : Token
            };


            // 取得會員資料
            HomeService homeService = new HomeService();
            GetCustInfoOutput result = await homeService.GetCustInfo(model);

            // 是否已綁定個人資料或代繳契約
            CustProxyPayStatus proxyPayStatus = await homeService.GetCustProxyPayStatus(model);
            if (string.IsNullOrEmpty(result.ID) ||
                proxyPayStatus.REG_COUNT < 3)
            {
                this.ViewBag.ShowAddButton = true;
            }
            else
            {
                this.ViewBag.ShowAddButton = false;
            }

            if (!string.IsNullOrEmpty(MbrId) && (string.IsNullOrEmpty(this.TokenVerify?.MbrId) || this.TokenVerify.MbrId != MbrId))
            {
                //// 取得會員資料
                //HomeService homeService = new HomeService();
                //GetCustInfoOutput result = await homeService.GetCustInfo(model);

                //// 是否已綁定個人資料或代繳契約
                //CustProxyPayStatus proxyPayStatus = await homeService.GetCustProxyPayStatus(model);
                //if (string.IsNullOrEmpty(result.ID) ||
                //    proxyPayStatus.REG_COUNT < 3)
                //{
                //    this.ViewBag.ShowAddButton = true;
                //}
                //else
                //{
                //    this.ViewBag.ShowAddButton = false;
                //}

                // 取得全資料
                InitOutput initOutput = await homeService.INIT(result.ID);

                // 加入Cookie
                System.Web.HttpCookie AridCookie = this.AirdCookie(result.ID ?? string.Empty, MbrId, DevId, Token, initOutput?.CUST_ID ?? string.Empty, initOutput?.CNTRT_NO ?? string.Empty);
                this.Response.Cookies.Add(AridCookie);
            }
            
            this.ViewBag.Title = "我的帳單";
            
            return this.View();
        }

        public ActionResult PaymentAR()
        {
            return this.View();
        }

        /// <summary>
        /// 繳款紀錄
        /// </summary>
        /// <returns></returns>
        public ActionResult Record()
        {
            return this.View();
        }

        public ActionResult RecordDetail()
        {
            return this.View();
        }

        public ActionResult PaymentList()
        {
            return this.View();
        }

        public ActionResult PaymentATM()
        {
            return this.View();
        }

        public ActionResult PaymentConStore()
        {
            return this.View();
        }

        public ActionResult Barcode()
        {
            return this.View();
        }

        public ActionResult Close()
        {
            return this.View();
        }

        public ActionResult Rescue()
        {
            return this.View();
        }

        public ActionResult Add()
        {
            return this.View();
        }
    }
}

CH_CAR_PFM/Views/Home/Add.cshtml

@{
    ViewBag.Title = "Add";
}




CH_CAR_PFM/Views/Home/Barcode.cshtml

@{
    ViewBag.Title = "繳款條碼";
}
@section header {
@Styles.Render("~/Content/pages/barcode.min.css") }

<div id="app">
    <div v-if="pageLoading" class="loading">
        <div class="loading-box">
            <img src="@Url.Content("~/Content/images/loading.gif")" alt="" class="loading-pic">
        </div>
    </div>

    <div class="header-box">
        <div class="header">
            <div class="header-back" v-on:click="pageBack"></div>
            <p class="header-title">@ViewBag.Title</p>
        </div>
    </div>
    <div class="barcode-container">
        <div class="barcode711">
            <img :src="'data:image.jpeg;base64,' + this.BarCodeImage" v-if="this.BarCodeImage != ''" class="avatar">
        </div>
        <div class="barcode">
            <img :src="'data:image.png;base64,' + this.BarCodeImage1" v-if="this.BarCodeImage1 != ''" class="avatar">
            <p class="barcode-text" v-text="barCode1"></p>
        </div>
        <div class="barcode">
            <img :src="'data:image.png;base64,' + this.BarCodeImage2" v-if="this.BarCodeImage2 != ''" class="avatar">
            <p class="barcode-text"  v-text="barCode2"></p>
        </div>
        <div class="barcode">
            <img :src="'data:image.png;base64,' + this.BarCodeImage3" v-if="this.BarCodeImage3 != ''" class="avatar">
            <p class="barcode-text"  v-text="barCode3"></p>
        </div>
    </div>
</div>


@section scripts {
    <script>
        var app = new Vue({
			el: '#app',
			mixins: [ myMixin ],
            data: {
                api: '@Url.Action("Get711BarCodeImg", "AppFormPay")',
                mmergeApi: '@Url.Action("GetMergeBarCode", "AppFormPay")',
                userPaymentList: [],
                paymentTotal: 0,
                barCode1: '',
                barCode2: '',
                barCode3: '',
                BarCodeImage: '',
                BarCodeImage1: '',
                BarCodeImage2: '',
                BarCodeImage3: '',
                storeType: 0,
                pageLoading: true
            },
            created: function() {
                this.getBarCode();
                if (this.storeType != 0) {
                    this.getBarCode_fm();
                }
                else {
                    this.getBarCode_711();
                }
            },
            methods: {
                getBarCode: function () {
                    try {
                        this.userPaymentList = JSON.parse(
                            sessionStorage.getItem("userPaymentList")
                        );
                        this.paymentTotal = sessionStorage.getItem("paymentTotal");
                        this.storeType = sessionStorage.getItem("storeType");
                    } catch {
                        alert("sesstion data error");
                        // this.pageBack();
                    }
                },
                getBarCode_711: function () {
                    console.log("getBarCode_711");
                    var vm = this;

                    axios.post(vm.api, {
                        arList: vm.userPaymentList
                    })
                    .then(function (response) {
                        vm.pageLoading = false;
                        if (response.data.Result.ReturnCode != '-1') {
                            vm.BarCodeImage = response.data.Data.barcode;
                        }
                        else {
                            alert(response.data.Result.Alert);
                        }
                    })
                    .catch(function (error) {
                        vm.pageLoading = false;
                        console.log(error)
                    });
                },
                getBarCode_fm: function () {
                    console.log("getBarCode_fm");
                    var vm = this;

                    axios.post(vm.mmergeApi, {
                        arList: vm.userPaymentList
                    })
                        .then(function (response) {
                            vm.pageLoading = false;
                            if (response.data.Result.ReturnCode != '-1') {
                                vm.barCode1 = response.data.Data.BARCODE1;
                                vm.barCode2 = response.data.Data.BARCODE2;
                                vm.barCode3 = response.data.Data.BARCODE3;
                                vm.BarCodeImage1 = response.data.Data.BarCodeImage1;
                                vm.BarCodeImage2 = response.data.Data.BarCodeImage2;
                                vm.BarCodeImage3 = response.data.Data.BarCodeImage3;
                            }
                            else {
                                alert(response.data.Result.Alert);
                            }
                        })
                        .catch(function (error) {
                            vm.pageLoading = false;
                            console.log(error)
                        });
                }
            }
        })
    </script>
}

CH_CAR_PFM/Views/Home/Close.cshtml

@{
    ViewBag.Title = "close";
}

<h2></h2>


CH_CAR_PFM/Views/Home/Index.cshtml
@section header {
    @Styles.Render("~/Content/pages/index.min.css")
}


<div id="app">
    <div v-if="pageLoading" class="loading">
        <div class="loading-box">
            <img src="@Url.Content("~/Content/images/loading.gif")" alt="" class="loading-pic">
        </div>
    </div>

    <div class="header-box">
        <div class="header">
            <a class="header-back" href="@Url.Content("~/home/close")"></a>
            <p class="header-title">@ViewBag.Title</p>
        </div>
        <div class="tabs">
            <div class="tabs-item active">繳款</div>
            <a class="tabs-item" href="@Url.Content("~/home/record")">繳款紀錄</a>
        </div>
    </div>

    <!-- page: 繳款 -->
    <div v-if="pageError" class="dashboard page-error" v-cloak>
        <p class="page-error--text">很抱歉！系統忙碌中，請稍後再試！</p>
    </div>
    <div v-else class="dashboard" v-cloak>
        <!-- data: .car = 一筆標的物 -->
        <car-element v-for="car in cars"
                     v-bind:key="car.id"
                     v-bind:car_data="car"
                     v-bind:ttl_amt="car.TTL_AMT"
                     v-bind:ar_dt="car.AR_DT"
                     v-bind:overdue="car.OVERDUE"
                     v-bind:cntrt_no="car.CNTRT_NO"></car-element>

        <!-- TODO: 若該帳號允許新增繳款資訊才顯示 -->
        <a href="@Url.Content("~/home/add")" class="add-payment"
            v-if="showAddBtn == 'False' ? false : true && appNeedShowBtn">                  
            <img src="@Url.Content("~/Content/images/ic_add_blue.png")" alt="">
            新增繳款資訊
        </a>

        <p class="care-text">
            溫馨提醒：<br />
            便利商店代收上限為新台幣6萬元，若帳單應繳金額超過代收上限，請您利用其他方式繳款。<br />
            ATM繳款帳號：<br />
            使用ATM或數位通路轉帳，若帳單應繳金額超過您的轉出帳戶銀行規定的最高轉出限額，您可向轉出帳戶銀行約定ATM繳款帳號或洽詢您的業務。
            <br />
            逾期延滯費用：<br />
            提醒您！逾期繳款將於最後一期清償時，依照契約條文收取延滯費用。
        </p>
    </div>
</div>

@section scripts {
    <script>
	const Car = Vue.component("car-element", {
        props: ["car_data", "ttl_amt", "ar_dt", "cntrt_no", "overdue"],
		data: function() {
			return {
				currentPeriodsIsFinish: 0,
				totalPeriods: 0,
                statusIsFinish: false
			};
		},
		created: function() {
			var vm = this;
            var ar_list = vm.car_data.AR_LIST;

            // 若該標的沒有任何一筆資料 => 沒有需要繳款資訊
            if (ar_list === null) {
                vm.statusIsFinish = true;
                return;
            }

            vm.isoverdue = ar_list.filter(x => x.OVERDUE === 'Y').length > 0;
            // console.log(vm.isoverdue);

			// or car_data.AR_LIST.length 取出該標的物的總期數
            vm.totalPeriods = ar_list[0].AR_CNT;

			// 確認該標的物已繳交期數
			var newArr = ar_list.map(function(value, index, array) {
				if (value.PAYMENT_STATUS === "1") {
					vm.currentPeriodsIsFinish += 1;
				}
			});
        },
		template: `<div class="car">
                <div class="car-header" >
                    <div class="car-header--number">
                        <div class="car-header--number-text" >車號&nbsp;I&nbsp;</div>
                        <div class="car-header--number-data"
                            v-bind:class="{ alertPoint: isoverdue }" >
                            <p v-for="item in car_data.OBJ_ITEMS" v-text="item.NME"></p>
                        </div>
                    </div>
                    <span class="car-header--periods"
                        v-if="!statusIsFinish && car_data.IS_PROXY !== 'Y'">
                        已繳 <span v-text="currentPeriodsIsFinish"></span> 期 /
                        共 <span v-text="totalPeriods"></span> 期</span>
                </div>
                <div v-if="statusIsFinish" class="car-status">
                    <p class="car-status--text">無繳款資訊</p>
                </div>
                <div v-else-if="car_data.IS_PROXY == 'Y'">
                    <ul class="car-content installment">
                        <li class="installment-item">
                            <div class="event">
                                <p class="event--title">應繳金額</p>
                                <p class="event--date"
                                    v-if="car_data.PAYABLE_AMT == 0">本期費用已繳清</p>
                                <p class="event--date" 
                                    v-else 
                                    v-text="'截止日' +ar_dt"></p>
                            </div>
                            <div class="amount" v-text="'$'+$options.filters.amountAddDot(car_data.PAYABLE_AMT)"></div>
                        </li>
                    </ul>
                    <a class="car-footer viewmore" v-bind:href="'@Url.Content("~/home/PaymentAR?id=")' + cntrt_no"
                        v-if="car_data.PAYABLE_AMT !== 0">
                        前往繳款<img src="@Url.Content("~/Content/images/arrow_right.svg")" alt="arrow">
                    </a>
                </div>
                <div v-else>
                    <ul class="car-content installment">
                        <li class="installment-item">
                            <div class="event">
                                <p class="event--title">案件總金額</p>
                                <p class="event--date" 
                                    v-text="'截止日' +ar_dt"></p>
                            </div>
                            <div class="amount" v-text="'$'+$options.filters.amountAddDot(ttl_amt)"></div>
                        </li>
                    </ul>
                    <a class="car-footer viewmore" v-bind:href="'@Url.Content("~/home/PaymentAR?id=")' + cntrt_no">
                        前往繳款<img src="@Url.Content("~/Content/images/arrow_right.svg")" alt="arrow">
                    </a>
                </div>

            </div>`
	});

	var app = new Vue({
		el: "#app",
		component: { Car },
		mixins: [ myMixin ],
		data: {
            userID: null,
            api: '@Url.Action("GetArLv1New", "AppFormPay")',
			cars: [],
            pageError: false,
            pageLoading: true,
            isoverdue: false,
            showAddBtn: false,
            appNeedShowBtn: false
		},
        created: function () {
            var vm = this;
            vm.showAddBtn = '@ViewBag.ShowAddButton'
            // console.log(vm.showAddBtn)

            // 2020/7/21 因APP版本新舊交替之緣故，需多判斷APP端傳來的參數，若有值且為Y and showAddBtn = true，該新增契約之按鈕才可顯示
            vm.appNeedShowBtn = this.getUrlParameter("show") === 'Y' ? true : false;

			axios.post(vm.api)
            .then(function (response) {
                vm.pageLoading = false;
                if (response.data.Result.ReturnCode != -1) {
                    // console.log(response.data.Data);
                    vm.cars = response.data.Data;
                }
                else {
                    alert.log(response.data.Result.Alert);
                    vm.pageError = true;
                }
			})
			.catch(function(error){
                vm.pageLoading = false;
                alert.log(error);
                vm.pageError = true;
			});
		}
	});
    </script>
}

CH_CAR_PFM/Views/Home/PaymentATM.cshtml
@{ ViewBag.Title = "ATM繳款"; } @section header {
@Styles.Render("~/Content/pages/paymentATM.min.css") }

<div id="app">
	<div class="header-box">
        <div class="header">
            <div class="header-back" v-on:click="pageBack"></div>
            <p class="header-title">@ViewBag.Title</p>
            <a href="@Url.Content("~/home/close")" class="header-close">完成</a>
        </div>
    </div>
	<div class="dashboard">
        <div class="card">
            <div class="card-header">
                <p class="card-header--title">繳款總額</p>
                <p class="card-header--amount" v-cloak>${{ paymentTotal | amountAddDot }}</p>
            </div>
            <div class="card-content">
                <p class="card-content--title">轉帳資訊</p>
                <div class="payment">
                    <div class="payment-item">
						<span>銀行代碼</span>
                        <span class="payment-item--data" v-cloak>{{bankCode}} {{bankName}}</span>
					</div>
					<div class="payment-item">
						<span>帳號</span>
                        <span class="payment-item--data" v-text="atmAccntno"></span>
					</div>
                </div>
            </div>
            <div class="card-footer">
                <p class="card-footer--desc">完成繳款後，<span>第二個營業日</span>，方可從「繳款紀錄」功能，查詢匯款資訊。
					<br><br>
					溫馨提醒：<br>
					您好，使用ATM或數位通路轉帳，若帳單應繳金額超過您的轉出帳戶銀行規定的最高轉出限額，您可向轉出帳戶銀行約定ATM繳款帳號或洽詢您的業務。
                </p>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <script>
        var app = new Vue({
			el: '#app',
			mixins: [ myMixin ],
            data: {
                api: '@Url.Action("GetMergeBarCode", "AppFormPay")',
                userArId: null,
                userArName: [],
                userPaymentList: [],
                userPaymentType: "",
                paymentTotal: 0,
                bankCode: '',
                bankName: '',
                atmAccntno: ''
            },
            created: function() {
                this.getUserPayment();
                this.getBarCode_fm();
            },
            methods: {
                getUserPayment: function() {
					try {
						this.userArId = sessionStorage.getItem("userArId");
						this.userArName = JSON.parse(
							sessionStorage.getItem("userArName")
						);
						this.userPaymentList = JSON.parse(
							sessionStorage.getItem("userPaymentList")
						);
						this.userPaymentType = sessionStorage.getItem(
							"userPaymentType"
						);
						this.paymentTotal = sessionStorage.getItem("paymentTotal");
					}catch {
						alert("sesstion data error");
						// this.pageBack();
					}
                },
                getBarCode_fm: function () {
                    console.log("getBarCode_fm");
                    var vm = this;

                    axios.post(vm.api, {
                        arList: vm.userPaymentList
                    })
                        .then(function (response) {
                            if (response.data.Result.ReturnCode != -1) {
                                vm.bankCode = response.data.Data.BANK_CODE;
                                vm.bankName = response.data.Data.BANK_NME;
                                vm.atmAccntno = response.data.Data.ATM_ACCNTNO;
                            }
                        })
                        .catch(function (error) {
                            console.log(error)
                        });
                }
            }
        })
    </script>
}